### ISSUE TITLE
Eventually input using IME doesn't work well in mozc /  Arch Linux / Cinnamon

### ISSUE THREAD

**Issue by ngr-t** [lyfeyaj/sublime-text-imfix#42] opened 2017-08-08 03:57 UTC
At first, thank you for making this fix. Basically it works well.
However, sometimes (several ten minutes after I start the editor) input from IME stops working like this (I hit `Enter` key to confirm the input at the last in this movie):
![peek 2017-08-08 12-25](https://user-images.githubusercontent.com/729653/29055043-0c9e2bd0-7c35-11e7-80f1-21a1eee6a846.gif)
When I restart ST3, it works well again, like: 
![peek 2017-08-08 12-32](https://user-images.githubusercontent.com/729653/29055141-b4c04c08-7c35-11e7-8be9-730d26aa67c1.gif)

So sorry but I've not yet grasped how this fix works, therefore I wonder how can I fix this.

My environment is:

  - OS: Arch Linux
  - DE: Cinnamon
  - GTK: 2.24.31
  - ST3: Build 3126 + this fix (I installed the one in Arch User Repository https://aur.archlinux.org/packages/sublime-text-dev-imfix2/ with yaourt)
  - IME: Fcitx + mozc

This has not yet been happened on any other application.
I know the information I provide is very poor to speculate the cause, but I would be very grateful if I can get any clue to solve this.
I'd appreciate your help.

**Comment by lyfeyaj** [comment] 2017-08-08 10:21
I update this repo with some bug fix. Try to re-run the script `./sublime-imfix` to see whether your problem can be fixed.

**Comment by ngr-t** [comment] 2017-08-08 15:07
Thank you for rapid response!
I updated to the latest commit, but unfortunately the problem still looks to remain. I will try to make the condition to reproduce it clear.

**Comment by lyfeyaj** [comment] 2017-08-08 15:29
It seems that the bug you encountered was an old bug that couldn't be fixed by now(not to my knowledge). It is caused by those `patching methods` injected into sublime text via `LD_PRELOAD` environment variable. 

Try to reproduce the problem with the following steps:

1. Open one sublime text editor, then activate input method and try to input some CJK words;
2. While keeping the first editor open, now start another sublime text editor and repeat the 1st step;
3. Now switch back to the first editor, and you may find that the IME stop working on that editor, but you still can input CJK words into the second editor.

If you can reproduce your problem by those steps. Then it is exactly the bug I described above.
The only way(as far as I know) to prevent that is trying not to open two sublime text editors at the same time.

Any further information, please let me know.

**Comment by ngr-t** [comment] 2017-08-09 02:17
I could reproduce the bug by the steps above. Also thank you for the workaround.
I will keep the number of window just one when I use IME. I will let you know if I find other workarounds or some further information.

**Closed** 2020-12-08 07:38 UTC
